fuelfinder/buyer/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views 
from django.conf import settings 
from django.conf.urls.static import static 

urlpatterns = [
    path('register', views.register, name='buyer-register'),
    path('login', auth_views.LoginView.as_view(template_name='buyer/login.html'), name='buyer-login'),
    path('logout', auth_views.LogoutView.as_view(template_name='buyer/logout.html'), name='buyer-logout'),
    path('profile', views.profile, name='buyer-profile'),
]

if settings.DEBUG: 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fuelfinder/fuelfinder/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('finder.urls')),
    path('register/', include('supplier.urls')),
    path('users/', include(('users.urls','users'), namespace='users')),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

fuelfinder/users/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from . import views

urlpatterns = [
    path('', views.index, name="home"),
    path('suppliers/', views.suppliers_list, name="suppliers_list"),
    path('supplier_user_create/<int:sid>', views.supplier_user_create, name="supplier_user_create"),
    # path('/index/', views.index, name="home")
    # path('/index/', views.index, name="home")

]

fuelfinder/users/models.py
from django.db import models
from django.dispatch import receiver

from supplier.models import *

from django.db import models
from django.contrib.auth.models import User
from django.contrib import messages

class SupplierContact(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    supplier_profile = models.ForeignKey(SupplierProfile,on_delete=models.CASCADE)
    telephone = models.CharField(max_length=300, blank=True)
    cellphone = models.CharField(max_length=300, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['user__last_name']

    def __str__(self):
        return self.cellphone

    def disable(self):
        self.user.active = False
        self.user.save()
        self.active = False
        self.save()

    def enable(self):
        self.user.active = True
        self.user.save()
        self.active = True
        self.save()

fuelfinder/users/forms.py
from datetime import timedelta, date

from django import forms
#from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from .models import *
from supplier.models import *
from django.contrib.auth.models import User
from users.models import *

from .utils import *
from .widgets.select_time_widget import *


def validate_user_email(value):
    safe = True
    if '@' in value:
        if User.objects.filter(email=value.strip()).exists():
            safe = False
    if not safe:
        raise ValidationError('%(value)s is already registered',
            params={'value': value},)

class SupplierContactForm(forms.Form):
    first_name = forms.CharField(label='First Name(s)', required=True,
                                max_length=30)
    last_name = forms.CharField(label='Last Name(s)', required=True,
                                 max_length=30)
    email = forms.EmailField(required=True, max_length=100,
                            validators=[validate_user_email])
    cellphone = forms.CharField(label='Cellphone number', required=True,
                                 max_length=100)
    telephone = forms.CharField(label='Telephone number', max_length=100,
                                required=False)
    password = forms.CharField(label='Password', required=True, max_length=100,
                             widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password Confirm', required=True,
                             widget=forms.PasswordInput, max_length=100)

    def clean(self):
        cleaned_data = super(SupplierContactForm, self).clean()
        password = cleaned_data.get("password")
        password2 = cleaned_data.get("password2")
        if password != password2:
            raise forms.ValidationError("The passwords do not match!")
class ActionForm(forms.Form):
    pass                    



   

fuelfinder/users/views.py
from django.shortcuts import render, get_object_or_404, redirect


from supplier.models import *
from supplier.forms import *
from .forms import *

from datetime import datetime

def index(request):
    return render(request, 'users/index.html')


def suppliers_list(request):
    suppliers = SupplierProfile.objects.all()
    return render(request, 'users/suppliers_list.html', {'suppliers': suppliers})

# Begining Of Supplier Management

def supplier_user_create(request, sid):
    supplier = get_object_or_404(SupplierProfile, id=sid) 
    if request.method == 'POST':
        user_count = SupplierContact.objects.filter(supplier_profile=supplier).count()
        if user_count > 50:
            raise Http404("Organisations has 50 users, delete some ")
        form = SupplierContactForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            cellphone = form.cleaned_data['cellphone']
            telephone = form.cleaned_data['telephone']

            user = User.objects.create_user(email, email, password)
            user.last_name = form.cleaned_data['last_name']
            user.first_name = form.cleaned_data['first_name']
            user.save()   
            contact = SupplierContact.objects.create(user=user, cellphone=cellphone, telephone=telephone, supplier_profile=supplier)
            #contact.save()
            messages.success(request, ('Your profile was successfully updated!'))
            return redirect('users:suppliers_list')
            
        
        else:
            msg = "Error in Information Submitted"
            messages.error(request, msg)
    else:
        form = SupplierContactForm()


    return render (request, 'users/add_user.html', {'form': form, 'supplier': supplier}) 

def edit_supplier(request,id):
    supplier = get_object_or_404(SupplierProfile, id=id)
    if request.method == "POST":
        form = UserForm(request.POST, request.FILES, instance=supplier)
        if form.is_valid():
            data = form.cleaned_data
            supplier = form.save()
            messages.success(request, 'Changes Successfully Update')
            return redirect('users.index')
    else:
        form = SupplierProfile(instance=supplier)
    return render(request, 'users/supplier_edit.html', {'form': form, 'supplier': supplier})

def delete_user(request,id):
    supplier = get_object_or_404(SupplierProfile, id=id)

    if request.method == 'POST':
        form = ActionForm(request.POST)
        if form.is_valid():
            supplier.delete()
            messages.success(request, 'User Has Been Deleted')
        return redirect('administrator:blog_all_posts')
    form = ActionForm()    

    return render(request, 'user/supplier_delete.html', {'form': form, 'supplier': supplier})

fuelfinder/users/templates/users/add_user.html
{% extends "users/base.html" %}
{% block body %}
<div class="jumbotron">
    <h1 class="display-3">Super User Dashboard</h1>
    <hr class="my-2">
    
    <p class="lead">
        {{ supplier.name }} Profile
    </p>
</div>

<div class="card text-white bg-info mb-3" style="max-width: 180rem;">
    <div class="card-header">{{ supplier.name }}</div>
    <div class="card-body">
      <h5 class="card-title"> {{ supplier.bpn }}</h5>
      <a button type="button" class="btn btn-primary" data-toggle="modal" data-target="#{{supplier.id}}">Add A New User.</a>
    </div>
  </div>

  <div class="modal fade" id="{{supplier.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Add User - {{ supplier.name }}</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">  

            {% load crispy_forms_tags %}
            <form action="{% url 'users:supplier_user_create' supplier.id %}" method="POST">
            {{ form|crispy }}
            {% csrf_token %}
            <button class="btn btn-primary" type="submit">Add User Profile</button>
            </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>    


{% endblock %}

fuelfinder/users/templates/users/index.html
{% extends "users/base.html" %}
{% block body %}
<div class="jumbotron">
    <h1 class="display-3">Super User Dashboard</h1>
    <hr class="my-2">
    <p>More info</p>
    <p class="lead">
        <a class="btn btn-primary btn-lg" href="Jumbo action link" role="button">Jumbo action name</a>
    </p>
</div>
{% endblock %}

fuelfinder/users/templates/users/suppliers_list.html
{% extends "users/base.html" %}
{% block body %}

<div class="jumbotron">
    <h1 class="display-3">Super User Dashboard</h1>
    <hr class="my-2">
    
    <p class="lead">
        Supplier Profiles
    </p>
</div>

<div class="col-md-12">
    <div class="card" style="background-color:white">
        <div class="card-header card-header-primary">
        <h4 class="card-title ">Supplier Profiles</h4>
        </div>
    <div class="card-body">
        <div class="container-fluid">
            {% if suppliers %}
            <table id="example" class="table table-striped table-bordered" style="width:100%">
                <thead style="color:white; background:lightslategray">
                    <th style="color:white;">
                        Name
                       </th>
                       <th style="color:white;">
                         BPN
                       </th>
                       <th style="color:white;">
                          Phone 
                         </th>
                         <th style="color:white;">
                           Street 
                          </th>
                          <th style="color:white;"></th>
                   <tbody>
                       {% for supplier in suppliers %}
                       <tr>
                           <td>{{supplier.name}}</td>
                           <td>{{supplier.bpn}}</td>
                           <td>{{supplier.phone}}</td>
                           <td>{{supplier.street}}</td>
                        <td><a href="{% url 'users:supplier_user_create' supplier.id %}" class="btn btn-primary">view Supplier</a></td>
                    </tr>
                    {% endfor %}    
                </tbody>
                </table>
            {% else %}
            <p>Nothing To SHow</p>    
            {% endif %}
        </div>
    </div>
    </div>
    
</div>
{% endblock %}